# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
