# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0003_article_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weights', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dates', models.DateField()),
            ],
        ),
    ]
